### ISSUE TITLE
eval:evalCommand not implemented?

### ISSUE THREAD

**Issue by rubenmoor** [emacs-lsp/lsp-haskell#102]
I type

```
{-
>>> foo
-}
```

And there appears

```evaluate```

If I click on it, I get the message

```
LSP :: Please open an issue in lsp-mode for implementing `12876:eval:evalCommand'.

```

Following the error message I posted an issue in the `lsp-mod` repo and they directed me back here.

https://github.com/emacs-lsp/lsp-mode/issues/2527

**Comment by michaelpj** [comment]
As noted in that issue, there is a `lsp-mode` bug, it's just that there's already an issue for it.

There should be an actual error message in the `haskell-language-server` log. If you find that, please report it in the `haskell-language-server` repo, rather than here (this is just the Emacs connector).
