### ISSUE TITLE
xref-find-definition for project dependencies

### ISSUE THREAD

**Issue by wpcarro** [emacs-lsp/lsp-haskell#23]
Loving `lsp-haskell` so far. Is it possible to have `xref-find-definition` for `Base` and a project's dependencies?

**Comment by wraithm** [comment]
Yes, I'm having issues with `xref-find-definition` in a multi-package project. It won't jump to a definition across package boundaries.

It would be great if `xref-find-definition` fell back to using tags if nothing is found in the current project.

**Comment by michaelpj** [comment]
For the LSP case, this is a `haskell-language-server` issue, which I think is already tracked (for example https://github.com/haskell/haskell-language-server/issues/44).

Re: falling back to tags, I think we shouldn't do more here since we're really just a client for `lsp-mode`. But we also recommend that people enable `haskell-mode`, which might add jump handlers that user tags?

**Comment by michaelpj** [comment]
Re: using tags, it seems that it's not currently possible to augment the `lsp-mode` xref backend with another one (https://gitter.im/emacs-lsp/lsp-mode?at=5f6c9a025efe9467b1127f85). So this is probably not something we can fix easily, unfortunately.
