### ISSUE TITLE
Enables flymake (for me)

### ISSUE THREAD

**Issue by vyorkin** [emacs-lsp/lsp-haskell#41]
Hello, thanks for `lsp-haskell`, it is pretty cool!

For some reason requiring (`(use-package lsp-haskell)`) enables the `flymake` mode for me. This is annoying because it creates an additional `"Foo_flymake.hs"` file for each `".hs"` file that I edit.

Here is my emacs config: https://github.com/vyorkin/emacs.d

**Comment by vyorkin** [comment]
ok, nevermind, turns out it is a default behavior of `lsp-mode`:

> Real-time Diagnostics/linting (via builtin flymake when Emacs > 26 or flycheck/lsp-ui)

> lsp-prefer-flymake - If you prefer flycheck and `lsp-ui-flycheck` is available, `(setq lsp-prefer-flymake nil)`. If set to `:none` neither of two will be enabled.

**Comment by timoffex** [comment]
For posterity:

- `lsp-prefer-flymake` seems to be deprecated and superseded by `lsp-diagnostic-package`, which is set to `:auto` by default. I think `:auto` means "pick flycheck if present and otherwise prefer flymake"
- Installing flycheck-haskell solved this problem for me. (https://github.com/flycheck/flycheck-haskell)
