### ISSUE TITLE
I should be able to kill my buffer if I manually killed the lsp process

### ISSUE THREAD

**Issue by Denommus** [emacs-lsp/lsp-haskell#7]
Ditto.

**Comment by michaelpj** [comment]
I'm not really sure what the issue is here. Is it that after you kill the server process emacs remains unresponsive? Or that you are somehow prevented from killing the buffer?

Regardless, I expect this is an issue for `lsp-mode` (or `haskell-language-server` if it's the server that's misbehaving): we don't control the interaction between emacs and the server apart from telling `lsp-mode` how to start it.
