### ISSUE TITLE
`lsp-haskell-server-wrapper-function` not being used?

### ISSUE THREAD

**Issue by thalesmg** [emacs-lsp/lsp-haskell#85]
Hello!

First, thanks for putting up this library! :beers: 

I'm trying to use this with `haskell-language-server` inside a nix sandbox. I tried to set some wrappers (following along the lines of [this gist](https://gist.github.com/sevanspowell/23b0135dae2834e59904a502b8a0eb5d)). But, according to `*lsp-haskell::stderr*`, I was always getting the `haskell-language-server-wrapper` that is in my path, not inside my sandbox. Which fails due to GHC version mismatch.

Searching `lsp-haskell.el`, I could not find any places that are using `lsp-haskell-server-wrapper-function`, which is supposedly the key piece here.

The only way I got it working was to alter the `:new-connection` from `lsp-register-client`:

```elisp
(lsp-register-client
  (make-lsp--client
   :new-connection (lsp-stdio-connection (lambda ()
                                           (apply
                                            lsp-haskell-server-wrapper-function ;; <--- had to add this
                                            (list (lsp-haskell--server-command)))))
    ...
    ))
```

... and then it correctly used the executable from inside my sandbox.

Is there something I'm missing? Or does this patch make sense?

**Comment by Anton-Latukha** [comment]
It took me a long time, (a day) to understand this.

**Comment by Anton-Latukha** [comment]
Wrapper was deleted in: 63baa1a30bc0ac734dffbda56451bc7df9c8b9ab.

When the:
```elisp
(defun lsp-haskell--hie-command ()
  (funcall lsp-haskell-process-wrapper-function (lsp--haskell-hie-command)))
```

Become:
```elisp
(defun lsp-haskell--server-command ()
  "Command and arguments for launching the inferior language server process.
These are assembled from the customizable variables `lsp-haskell-server-path'
and `lsp-haskell-server-args'."
  (append (list lsp-haskell-server-path "--lsp") lsp-haskell-server-args) )
```

**Comment by Anton-Latukha** [comment]
And as we see, the HLS 0.5.0 `haskell-language-server-wrapper` does not support automatic loading of the Nix environements. (NOR it probably would by default - HLS would probably opt-out loading Nix env by default, if only for NixOS), so currently reintroducing wrapper, for future and backward compatibility seems most proper.

**Comment by Anton-Latukha** [comment]
Submitted a PR with fix :arrow_up:.

**Comment by michaelpj** [comment]
Fixed now, thanks.

If you want to load something from the Nix environment, I would suggest using `direnv` with `lorri` and `direnv-mode` in Emacs. In my experience this works well.

**Comment by Anton-Latukha** [comment]
To reduce effort of IDEs, currently, I started work on optional Nix env loading support diretly by HLS wraper, so HLS Nix env support would be standartized for all IDEs and to reduce wraping of HLS wrapper into wrapper for IDEs.

It is reasonable case, it person/configuration requests loading of the Nix env - and start HLS wrapper there anew in a classical way, essentially as `lsp-haskell` does it.

But `lsp-haskell` recommends it in a partial way, currently, since - there is an option of `shell.nix` not being available - then `nix-shell` simply loads `default.nix` (which is always possible) - that is default behaviour. And `shell.nix` can be in `../` or further up the tree.

I would submit PR with that, but that is up to you to accept it, since it requires a dependency use.

**Comment by michaelpj** [comment]
I think the wrapper function we have is a bit of a hack. I'd rather suggest that people use `direnv-mode`!
