### ISSUE TITLE
Implement 21444:eval:evalCommand

### ISSUE THREAD

**Issue by jmorag** [emacs-lsp/lsp-haskell#89]
**Describe the bug**
The haskell-language-server [eval feature](https://github.com/haskell/haskell-language-server#features) is unsupported.

**To Reproduce**
Attempt to evaluate the code lens appearing over
-- >>> 1 + 1

in a Haskell file with a working lsp session.

**Expected behavior**
The evaluation result should appear as a comment under the expression line

**Which Language Server did you use**
haskell-language-server

**OS**
NixOS

**Error callstack**
(error "BadDependency \"GhcSessionDeps\"")
LSP :: Please open an issue in lsp-mode for implementing `21444:eval:evalCommand'.

**Comment by michaelpj** [comment]
Hmm, this is odd. You do see a code lens? I actually don't see a code lens in Emacs, although I do see one in vscode, which is quite strange, since I don't think there's anything special about that code lens as opposed to any others.

If you do see the lens but you get that error from the server, that sounds like a server bug.

**Comment by michaelpj** [comment]
Ah, the former issue is something in `lsp-mode` about showing code lenses. If I run `lsp-lens-show` it shows the lens, and it works for me.

So I think this may be a server bug: can you open it upstream? I'll see if I can figure out what's going on with the showing of the code lens.

**Comment by michaelpj** [comment]
Well, I figured that bit out: the eval plugin isn't configured to act as a code action at all.
